update service file

diff --git a/SofaSurfer/templates/sofasurfer_service.erb b/SofaSurfer/templates/sofasurfer_service.erb
--- a/SofaSurfer/templates/sofasurfer_service.erb
+++ b/SofaSurfer/templates/sofasurfer_service.erb
@@ -1,44 +1,110 @@
-include_recipe "ruby-ng::dev"
-include_recipe "nodejs"
-include_recipe "nodejs::npm"
-include_recipe "postgres"
-include_recipe "nginx"
-include_recipe "unicorn"
+#!/bin/sh
+### BEGIN INIT INFO
+# Provides:
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Start daemon at boot time
+# Description:       Enable service provided by daemon.
+### END INIT INFO
 
-apt_package 'zlib1g-dev'
-apt_package 'libpq-dev'
+dir="<%= node[:SofaSurfer][:path] %>"
+cmd="<%= node[:SofaSurfer][:start_cmd] %>"
+# user="root"
 
-template "sofasurfer_service" do
-    path "/etc/init.d/sofasurfer"
-    source "sofasurfer_service.erb"
-    owner "root"
-    group "root"
-    mode "0755"
-end
+name=`basename $0`
+pid_file="/var/run/$name.pid"
+stdout_log="/var/log/$name.log"
+stderr_log="/var/log/$name.err"
 
-service "SofaSurfer" do
-  supports :restart => true, :start => true, :stop => true, :reload => true
-  action [ :enable ]
-end
+get_pid() {
+    cat "$pid_file"
+}
 
-template "#{node['nginx']['dir']}/sites-available/sofasurfer" do
-  source 'sofasurfer_site.erb'
-  notifies :reload, 'service[nginx]', :delayed
-end
+is_running() {
+    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
+}
 
-nginx_site 'SofaSurfer' do
-  action :enable
-end
+case "$1" in
+    start)
+    if is_running; then
+        echo "Already started"
+    else
+        echo "Starting $name"
+        cd "$dir"
 
-directory '/tmp/sockets/' do
-  owner 'root'
-  group 'root'
-  mode '0777'
-  action :create
-end
+        <% if node[:SofaSurfer].attribute?('cdn_host') %>
+        git_commit=`cd ${dir}; git rev-parse HEAD`
+        export CDN_HOST="<%= node[:SofaSurfer][:cdn_host] %>/${git_commit}/"
+        <% else %>
+        export RAILS_SERVE_STATIC_FILES="true"
+        <% end %>
+        <% node[:SofaSurfer][:environment].each do |k, v| %>
+        export <%= k%>="<%= v%>"
+        <% end %>
 
-unicorn_config "/opt/unicorn.rb" do
-  listen ({"unix:/tmp/sockets/unicorn.sock": nil})
-  working_directory node[:SofaSurfer][:path]
-  # /config/unicorn.rb
-end
+        if [ -z "$user" ]; then
+            sudo -E $cmd >> "$stdout_log" 2>> "$stderr_log" &
+        else
+            sudo -E -H -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
+        fi
+        echo $! > "$pid_file"
+        if ! is_running; then
+            echo "Unable to start, see $stdout_log and $stderr_log"
+            exit 1
+        fi
+    fi
+    ;;
+    stop)
+    if is_running; then
+        echo -n "Stopping $name.."
+        kill `get_pid`
+        for i in 1 2 3 4 5 6 7 8 9 10
+        # for i in `seq 10`
+        do
+            if ! is_running; then
+                break
+            fi
+
+            echo -n "."
+            sleep 1
+        done
+        echo
+
+        if is_running; then
+            echo "Not stopped; may still be shutting down or shutdown may have failed"
+            exit 1
+        else
+            echo "Stopped"
+            if [ -f "$pid_file" ]; then
+                rm "$pid_file"
+            fi
+        fi
+    else
+        echo "Not running"
+    fi
+    ;;
+    restart)
+    $0 stop
+    if is_running; then
+        echo "Unable to stop, will not attempt to start"
+        exit 1
+    fi
+    $0 start
+    ;;
+    status)
+    if is_running; then
+        echo "Running"
+    else
+        echo "Stopped"
+        exit 1
+    fi
+    ;;
+    *)
+    echo "Usage: $0 {start|stop|restart|status}"
+    exit 1
+    ;;
+esac
+
+exit 0
